import type { AuthoredWorldV3, Vec2 } from "../contracts/world.ts"

const rectangle = (
  minX: number,
  minZ: number,
  maxX: number,
  maxZ: number
): Vec2[] => [
  [minX, minZ],
  [maxX, minZ],
  [maxX, maxZ],
  [minX, maxZ],
]

/**
 * The complete schema-V3 Journey world.
 *
 * Only the spatial sequence is authored here. Portfolio copy remains in the
 * canonical DOM manifest and is joined by recordId. Buildings, vegetation,
 * terrain, water and bridges are environmental scenery generated from code.
 */
export const JOURNEY_V3_WORLD: AuthoredWorldV3 = {
  schemaVersion: 3,
  scope: "complete",
  seed: 20250723,
  bounds: [-80, -240, 80, 40],
  cellSize: 40,
  terrainSampleSpacing: 4,
  roadSampleSpacing: 2,
  waterLevel: 0.06,
  spawn: [-0.5, 29],
  districts: [
    { id: "town", kind: "about", order: 0 },
    { id: "education", kind: "education", order: 1 },
    { id: "career", kind: "career", order: 2 },
    { id: "learning", kind: "learning", order: 3 },
    { id: "projects", kind: "projects", order: 4 },
    { id: "community", kind: "community", order: 5 },
    { id: "contact", kind: "contact", order: 6 },
  ],
  nodes: [
    { id: "journey-north", position: [0, 34] },
    { id: "journey-south", position: [18, -222] },
  ],
  roads: [
    {
      id: "journey-spine",
      from: "journey-north",
      to: "journey-south",
      width: 7.2,
      endTurnaroundRadius: 4.8,
      controlPoints: [
        [0, 34],
        [-4, 16],
        [2, -4],
        [-5, -25],
        [0, -47],
        [8, -68],
        [14, -90],
        [8, -112],
        [18, -133],
        [10, -153],
        [-2, -174],
        [8, -197],
        [18, -222],
      ],
      districtId: "town",
      journeyLine: true,
    },
  ],
  portfolioRecords: [
    { recordId: "town-square", districtId: "town", routeOrder: 0 },
    {
      recordId: "rangpur-zilla-school",
      districtId: "education",
      routeOrder: 1,
    },
    {
      recordId: "carmichael-college",
      districtId: "education",
      routeOrder: 2,
    },
    { recordId: "baust", districtId: "education", routeOrder: 3 },
    {
      recordId: "codez-info-tech",
      districtId: "career",
      routeOrder: 4,
    },
    { recordId: "drra", districtId: "career", routeOrder: 5 },
    {
      recordId: "multiversal-software",
      districtId: "career",
      routeOrder: 6,
    },
    { recordId: "mymedicalhub", districtId: "career", routeOrder: 7 },
    {
      recordId: "learning-library",
      districtId: "learning",
      routeOrder: 8,
    },
    {
      recordId: "project-workshop",
      districtId: "projects",
      routeOrder: 9,
    },
    {
      recordId: "community-hall",
      districtId: "community",
      routeOrder: 10,
    },
    {
      recordId: "contact-pavilion",
      districtId: "contact",
      routeOrder: 11,
    },
  ],
  checkpoints: [
    {
      id: "checkpoint.town-square",
      recordId: "town-square",
      districtId: "town",
      roadId: "journey-spine",
      arrivalBuildingId: "structure.arrival-00",
      roadProgress: 0.04,
      roadSide: -1,
      offset: 7.6,
      interactionRadius: 3,
    },
    {
      id: "checkpoint.rangpur-zilla-school",
      recordId: "rangpur-zilla-school",
      districtId: "education",
      roadId: "journey-spine",
      arrivalBuildingId: "structure.arrival-01",
      roadProgress: 0.12,
      roadSide: 1,
      offset: 7.6,
      interactionRadius: 3,
    },
    {
      id: "checkpoint.carmichael-college",
      recordId: "carmichael-college",
      districtId: "education",
      roadId: "journey-spine",
      arrivalBuildingId: "structure.arrival-02",
      roadProgress: 0.2,
      roadSide: -1,
      offset: 7.6,
      interactionRadius: 3,
    },
    {
      id: "checkpoint.baust",
      recordId: "baust",
      districtId: "education",
      roadId: "journey-spine",
      arrivalBuildingId: "structure.arrival-03",
      roadProgress: 0.28,
      roadSide: 1,
      offset: 7.8,
      interactionRadius: 3,
    },
    {
      id: "checkpoint.codez-info-tech",
      recordId: "codez-info-tech",
      districtId: "career",
      roadId: "journey-spine",
      arrivalBuildingId: "structure.arrival-04",
      roadProgress: 0.435,
      roadSide: -1,
      offset: 7.6,
      interactionRadius: 3,
    },
    {
      id: "checkpoint.drra",
      recordId: "drra",
      districtId: "career",
      roadId: "journey-spine",
      arrivalBuildingId: "structure.arrival-05",
      roadProgress: 0.48,
      roadSide: 1,
      offset: 7.6,
      interactionRadius: 3,
    },
    {
      id: "checkpoint.multiversal-software",
      recordId: "multiversal-software",
      districtId: "career",
      roadId: "journey-spine",
      arrivalBuildingId: "structure.arrival-06",
      roadProgress: 0.52,
      roadSide: -1,
      offset: 7.6,
      interactionRadius: 3,
    },
    {
      id: "checkpoint.mymedicalhub",
      recordId: "mymedicalhub",
      districtId: "career",
      roadId: "journey-spine",
      arrivalBuildingId: "structure.arrival-07",
      roadProgress: 0.58,
      roadSide: -1,
      offset: 7.8,
      interactionRadius: 3,
    },
    {
      id: "checkpoint.learning-library",
      recordId: "learning-library",
      districtId: "learning",
      roadId: "journey-spine",
      arrivalBuildingId: "structure.arrival-08",
      roadProgress: 0.78,
      roadSide: 1,
      offset: 7.6,
      interactionRadius: 3,
    },
    {
      id: "checkpoint.project-workshop",
      recordId: "project-workshop",
      districtId: "projects",
      roadId: "journey-spine",
      arrivalBuildingId: "structure.arrival-09",
      roadProgress: 0.9,
      roadSide: 1,
      offset: 7.6,
      interactionRadius: 3,
    },
    {
      id: "checkpoint.community-hall",
      recordId: "community-hall",
      districtId: "community",
      roadId: "journey-spine",
      arrivalBuildingId: "structure.arrival-10",
      roadProgress: 0.9,
      roadSide: -1,
      offset: 7.6,
      interactionRadius: 3,
    },
    {
      id: "checkpoint.contact-pavilion",
      recordId: "contact-pavilion",
      districtId: "contact",
      roadId: "journey-spine",
      arrivalBuildingId: "structure.arrival-11",
      roadProgress: 0.97,
      roadSide: -1,
      offset: 7.6,
      interactionRadius: 3,
    },
  ],
  waterBodies: [
    {
      id: "water.northern-river",
      kind: "river",
      centerline: [
        [-80, -56],
        [-52, -59],
        [-25, -57],
        [4, -60],
        [34, -56],
        [80, -59],
      ],
      width: 22.32,
      waterLevel: -0.3,
      flowDirection: [1, -0.04],
      flowSpeed: 0.52,
      flowStrength: 0.88,
    },
    {
      id: "water.career-pond",
      kind: "pond",
      polygon: [
        [31, -135],
        [39, -138],
        [48, -134],
        [52, -126],
        [48, -117],
        [39, -113],
        [30, -118],
        [27, -127],
      ],
      waterLevel: -0.26,
      flowDirection: [0.38, -0.92],
      flowSpeed: 0.14,
      flowStrength: 0.34,
    },
    {
      id: "water.coastal-creek",
      kind: "river",
      centerline: [
        [-80, -146],
        [-55, -144],
        [-31, -147],
        [-7, -145],
        [21, -148],
        [49, -144],
        [80, -147],
      ],
      width: 17.28,
      waterLevel: -0.31,
      flowDirection: [1, 0.05],
      flowSpeed: 0.48,
      flowStrength: 0.82,
      bridgeLateralOffset: 0.9,
      bridgeDryLandingFactor: 0.14,
    },
    {
      id: "water.western-ocean",
      kind: "ocean",
      polygon: [
        [-80, -240],
        [-31, -240],
        [-34, -220],
        [-38, -199],
        [-35, -180],
        [-41, -159],
        [-47, -137],
        [-80, -130],
      ],
      islands: [
        [
          [-66, -193],
          [-58, -197],
          [-49, -193],
          [-46, -184],
          [-50, -174],
          [-58, -169],
          [-67, -174],
          [-71, -184],
        ],
      ],
      waterLevel: 0.08,
      flowDirection: [0.72, -0.28],
      flowSpeed: 0.11,
      flowStrength: 0.24,
    },
    {
      id: "water.contact-garden-pond",
      kind: "pond",
      polygon: [
        [38, -215],
        [45, -217],
        [51, -213],
        [53, -206],
        [49, -200],
        [42, -198],
        [36, -202],
        [34, -209],
      ],
      waterLevel: -0.27,
      flowDirection: [-0.26, -0.97],
      flowSpeed: 0.12,
      flowStrength: 0.3,
    },
  ],
  biomes: [
    {
      id: "biome.settlement",
      kind: "settlement",
      polygon: rectangle(-80, -240, 80, 40),
      treeDensity: 0.46,
      grassDensity: 0.64,
    },
    {
      id: "biome.northern-meadow",
      kind: "meadow",
      polygon: rectangle(-80, -42, 80, 40),
      treeDensity: 0.55,
      grassDensity: 0.84,
    },
    {
      id: "biome.northern-riparian",
      kind: "riparian",
      polygon: rectangle(-80, -69, 80, -48),
      treeDensity: 0.76,
      grassDensity: 0.92,
    },
    {
      id: "biome.career-wetland",
      kind: "wetland",
      polygon: rectangle(22, -143, 58, -106),
      treeDensity: 0.72,
      grassDensity: 0.9,
    },
    {
      id: "biome.coastal-riparian",
      kind: "riparian",
      polygon: rectangle(-80, -157, 80, -134),
      treeDensity: 0.7,
      grassDensity: 0.9,
    },
    {
      id: "biome.western-coast",
      kind: "coast",
      polygon: rectangle(-80, -240, -27, -125),
      treeDensity: 0.32,
      grassDensity: 0.4,
    },
    {
      id: "biome.contact-garden",
      kind: "meadow",
      polygon: rectangle(-5, -232, 62, -190),
      treeDensity: 0.62,
      grassDensity: 0.88,
    },
  ],
  environmentalBuildings: [
    {
      id: "structure.arrival-00",
      family: "homestead-hipped",
      archetype: "town-pavilion",
      districtId: "town",
      roadId: "journey-spine",
      roadProgress: 0.04,
      roadSide: -1,
      setback: 8.1,
      footprint: [16, 11],
      storeys: 1,
    },
    {
      id: "structure.arrival-01",
      family: "homestead-hipped",
      archetype: "schoolhouse",
      districtId: "education",
      roadId: "journey-spine",
      roadProgress: 0.12,
      roadSide: 1,
      setback: 8.1,
      footprint: [11.5, 7.5],
      storeys: 2,
    },
    {
      id: "structure.arrival-02",
      family: "homestead-gable",
      archetype: "academic-hall",
      districtId: "education",
      roadId: "journey-spine",
      roadProgress: 0.2,
      roadSide: -1,
      setback: 8.1,
      footprint: [12, 8],
      storeys: 2,
    },
    {
      id: "structure.arrival-03",
      family: "tin-roof-cottage",
      archetype: "engineering-campus",
      districtId: "education",
      roadId: "journey-spine",
      roadProgress: 0.28,
      roadSide: 1,
      setback: 8.1,
      footprint: [11.5, 7.5],
      storeys: 2,
    },
    {
      id: "structure.arrival-04",
      family: "homestead-hipped",
      archetype: "tech-office",
      districtId: "career",
      roadId: "journey-spine",
      roadProgress: 0.435,
      roadSide: -1,
      setback: 8.1,
      footprint: [10.5, 7],
      storeys: 2,
    },
    {
      id: "structure.arrival-05",
      family: "tin-roof-cottage",
      archetype: "service-centre",
      districtId: "career",
      roadId: "journey-spine",
      roadProgress: 0.48,
      roadSide: 1,
      setback: 8.1,
      footprint: [10, 6.8],
      storeys: 1,
    },
    {
      id: "structure.arrival-06",
      family: "homestead-gable",
      archetype: "software-studio",
      districtId: "career",
      roadId: "journey-spine",
      roadProgress: 0.52,
      roadSide: -1,
      setback: 8.1,
      footprint: [10.5, 7.2],
      storeys: 2,
    },
    {
      id: "structure.arrival-07",
      family: "homestead-hipped",
      archetype: "health-clinic",
      districtId: "career",
      roadId: "journey-spine",
      roadProgress: 0.58,
      roadSide: -1,
      setback: 8.1,
      footprint: [11, 7.2],
      storeys: 2,
    },
    {
      id: "structure.arrival-08",
      family: "homestead-hipped",
      archetype: "reading-room",
      districtId: "learning",
      roadId: "journey-spine",
      roadProgress: 0.78,
      roadSide: 1,
      setback: 8.1,
      footprint: [10.5, 7],
      storeys: 2,
    },
    {
      id: "structure.arrival-09",
      family: "tin-roof-cottage",
      archetype: "maker-workshop",
      districtId: "projects",
      roadId: "journey-spine",
      roadProgress: 0.9,
      roadSide: 1,
      setback: 8.1,
      footprint: [9.5, 6.5],
      storeys: 1,
    },
    {
      id: "structure.arrival-10",
      family: "homestead-gable",
      archetype: "community-hall",
      districtId: "community",
      roadId: "journey-spine",
      roadProgress: 0.9,
      roadSide: -1,
      setback: 8.1,
      footprint: [12, 8],
      storeys: 2,
    },
    {
      id: "structure.arrival-11",
      family: "homestead-hipped",
      archetype: "garden-pavilion",
      districtId: "contact",
      roadId: "journey-spine",
      roadProgress: 0.97,
      roadSide: -1,
      setback: 8.1,
      footprint: [10.5, 7.2],
      storeys: 1,
    },
  ],
} as const

/** Compatibility alias for early V3 imports; the default world is now full. */
export const JOURNEY_V3_VERTICAL_SLICE = JOURNEY_V3_WORLD
