import type { AuthoredWorld } from "../contracts/world.ts"

/**
 * The only hand-authored spatial source for Journey V2.
 *
 * Coordinates are metres in a flat X/Z plane. Everything else—including road
 * meshes, junctions, plots, colliders, navigation, scenery and cells—is derived
 * deterministically by the compiler.
 */
export const JOURNEY_V2_WORLD: AuthoredWorld = {
  seed: 20250723,
  cellSize: 40,
  roadSampleSpacing: 2.4,
  sidewalkWidth: 1.8,
  curbWidth: 0.24,
  districts: [
    { id: "town", kind: "about", order: 0 },
    { id: "education", kind: "education", order: 1 },
    { id: "career", kind: "career", order: 2 },
    { id: "learning", kind: "learning", order: 3 },
    { id: "projects", kind: "projects", order: 4 },
    { id: "community", kind: "community", order: 5 },
    { id: "contact", kind: "contact", order: 6 },
  ],
  nodes: [
    { id: "north-gate", position: [0, 20] },
    { id: "town-junction", position: [0, 0] },
    { id: "school-junction", position: [5, -36] },
    { id: "college-junction", position: [-2, -72] },
    { id: "baust-junction", position: [8, -108] },
    { id: "codez-junction", position: [3, -144] },
    { id: "drra-junction", position: [14, -180] },
    { id: "multiversal-junction", position: [8, -216] },
    { id: "medical-junction", position: [18, -252] },
    { id: "evidence-junction", position: [10, -284] },
    { id: "contact-end", position: [16, -324] },
    { id: "learning-end", position: [50, -224] },
    { id: "projects-end", position: [-29, -261] },
    { id: "community-end", position: [52, -296] },
  ],
  roads: [
    {
      id: "spine-town",
      from: "north-gate",
      to: "town-junction",
      width: 7.2,
      controlPoints: [
        [0, 20],
        [-1, 10],
        [0, 0],
      ],
      districtId: "town",
      journeyLine: true,
    },
    {
      id: "spine-school",
      from: "town-junction",
      to: "school-junction",
      width: 7.2,
      controlPoints: [
        [0, 0],
        [-2, -12],
        [1, -24],
        [5, -36],
      ],
      districtId: "education",
      journeyLine: true,
    },
    {
      id: "spine-college",
      from: "school-junction",
      to: "college-junction",
      width: 7.2,
      controlPoints: [
        [5, -36],
        [8, -47],
        [3, -60],
        [-2, -72],
      ],
      districtId: "education",
      journeyLine: true,
    },
    {
      id: "spine-baust",
      from: "college-junction",
      to: "baust-junction",
      width: 7.2,
      controlPoints: [
        [-2, -72],
        [-5, -84],
        [2, -96],
        [8, -108],
      ],
      districtId: "education",
      journeyLine: true,
    },
    {
      id: "spine-codez",
      from: "baust-junction",
      to: "codez-junction",
      width: 7.2,
      controlPoints: [
        [8, -108],
        [12, -120],
        [8, -133],
        [3, -144],
      ],
      districtId: "career",
      journeyLine: true,
    },
    {
      id: "spine-drra",
      from: "codez-junction",
      to: "drra-junction",
      width: 7.2,
      controlPoints: [
        [3, -144],
        [-1, -156],
        [6, -169],
        [14, -180],
      ],
      districtId: "career",
      journeyLine: true,
    },
    {
      id: "spine-multiversal",
      from: "drra-junction",
      to: "multiversal-junction",
      width: 7.2,
      controlPoints: [
        [14, -180],
        [18, -192],
        [14, -204],
        [8, -216],
      ],
      districtId: "career",
      journeyLine: true,
    },
    {
      id: "spine-medical",
      from: "multiversal-junction",
      to: "medical-junction",
      width: 7.2,
      controlPoints: [
        [8, -216],
        [4, -228],
        [10, -241],
        [18, -252],
      ],
      districtId: "career",
      journeyLine: true,
    },
    {
      id: "spine-evidence",
      from: "medical-junction",
      to: "evidence-junction",
      width: 7.2,
      controlPoints: [
        [18, -252],
        [21, -263],
        [16, -274],
        [10, -284],
      ],
      districtId: "contact",
      journeyLine: true,
    },
    {
      id: "spine-contact",
      from: "evidence-junction",
      to: "contact-end",
      width: 7.2,
      controlPoints: [
        [10, -284],
        [6, -297],
        [10, -311],
        [16, -324],
      ],
      districtId: "contact",
      journeyLine: true,
    },
    {
      id: "branch-learning",
      from: "multiversal-junction",
      to: "learning-end",
      width: 6.4,
      controlPoints: [
        [8, -216],
        [21, -211],
        [36, -215],
        [50, -224],
      ],
      districtId: "learning",
      journeyLine: false,
    },
    {
      id: "branch-projects",
      from: "medical-junction",
      to: "projects-end",
      width: 6.4,
      controlPoints: [
        [18, -252],
        [5, -247],
        [-12, -252],
        [-29, -261],
      ],
      districtId: "projects",
      journeyLine: false,
    },
    {
      id: "branch-community",
      from: "evidence-junction",
      to: "community-end",
      width: 6.4,
      controlPoints: [
        [10, -284],
        [23, -280],
        [38, -286],
        [52, -296],
      ],
      districtId: "community",
      journeyLine: false,
    },
  ],
  crosswalks: [
    {
      id: "crosswalk-town",
      roadId: "spine-school",
      progress: 0.12,
      width: 3.2,
    },
    {
      id: "crosswalk-school",
      roadId: "spine-school",
      progress: 0.54,
      width: 3.2,
    },
    {
      id: "crosswalk-college",
      roadId: "spine-college",
      progress: 0.5,
      width: 3.2,
    },
    {
      id: "crosswalk-baust",
      roadId: "spine-baust",
      progress: 0.52,
      width: 3.2,
    },
    {
      id: "crosswalk-codez",
      roadId: "spine-codez",
      progress: 0.5,
      width: 3.2,
    },
    {
      id: "crosswalk-drra",
      roadId: "spine-drra",
      progress: 0.51,
      width: 3.2,
    },
    {
      id: "crosswalk-multiversal",
      roadId: "spine-multiversal",
      progress: 0.5,
      width: 3.2,
    },
    {
      id: "crosswalk-medical",
      roadId: "spine-medical",
      progress: 0.52,
      width: 3.2,
    },
    {
      id: "crosswalk-learning",
      roadId: "branch-learning",
      progress: 0.2,
      width: 3,
    },
    {
      id: "crosswalk-projects",
      roadId: "branch-projects",
      progress: 0.2,
      width: 3,
    },
    {
      id: "crosswalk-community",
      roadId: "branch-community",
      progress: 0.2,
      width: 3,
    },
    {
      id: "crosswalk-contact",
      roadId: "spine-contact",
      progress: 0.68,
      width: 3.2,
    },
  ],
  landmarks: [
    {
      id: "town-square",
      title: "Montasim's Town Square",
      shortTitle: "Town Square",
      districtId: "town",
      kind: "chronology",
      routeOrder: 0,
      roadId: "spine-town",
      roadProgress: 0.55,
      roadSide: -1,
      setback: 5.5,
      footprint: [13, 8],
      height: 5.5,
      style: "civic",
    },
    {
      id: "rangpur-zilla-school",
      title: "Rangpur Zilla School",
      shortTitle: "Rangpur Zilla School",
      districtId: "education",
      kind: "chronology",
      routeOrder: 1,
      roadId: "spine-school",
      roadProgress: 0.54,
      roadSide: 1,
      setback: 6.5,
      footprint: [16, 9],
      height: 6.4,
      style: "school",
    },
    {
      id: "carmichael-college",
      title: "Carmichael College",
      shortTitle: "Carmichael College",
      districtId: "education",
      kind: "chronology",
      routeOrder: 2,
      roadId: "spine-college",
      roadProgress: 0.5,
      roadSide: -1,
      setback: 6.8,
      footprint: [18, 10],
      height: 7.2,
      style: "college",
    },
    {
      id: "baust",
      title: "Bangladesh Army University of Science and Technology",
      shortTitle: "BAUST",
      districtId: "education",
      kind: "chronology",
      routeOrder: 3,
      roadId: "spine-baust",
      roadProgress: 0.52,
      roadSide: 1,
      setback: 7.4,
      footprint: [20, 12],
      height: 8,
      style: "campus",
    },
    {
      id: "codez-info-tech",
      title: "Codez Info Tech",
      shortTitle: "Codez Info Tech",
      districtId: "career",
      kind: "chronology",
      routeOrder: 4,
      roadId: "spine-codez",
      roadProgress: 0.5,
      roadSide: -1,
      setback: 5.8,
      footprint: [12, 8],
      height: 6.2,
      style: "office",
    },
    {
      id: "drra",
      title: "Disabled Rehabilitation and Research Association",
      shortTitle: "DRRA",
      districtId: "career",
      kind: "chronology",
      routeOrder: 5,
      roadId: "spine-drra",
      roadProgress: 0.51,
      roadSide: 1,
      setback: 6.2,
      footprint: [14, 9],
      height: 6.8,
      style: "office",
    },
    {
      id: "multiversal-software",
      title: "Multiversal Software",
      shortTitle: "Multiversal",
      districtId: "career",
      kind: "chronology",
      routeOrder: 6,
      roadId: "spine-multiversal",
      roadProgress: 0.5,
      roadSide: -1,
      setback: 6,
      footprint: [13, 8],
      height: 6.4,
      style: "office",
    },
    {
      id: "mymedicalhub",
      title: "MyMedicalHub",
      shortTitle: "MyMedicalHub",
      districtId: "career",
      kind: "chronology",
      routeOrder: 7,
      roadId: "spine-medical",
      roadProgress: 0.52,
      roadSide: 1,
      setback: 6.8,
      footprint: [17, 10],
      height: 7.6,
      style: "office",
    },
    {
      id: "learning-library",
      title: "Learning Library",
      shortTitle: "Learning",
      districtId: "learning",
      kind: "evidence",
      routeOrder: 8,
      roadId: "branch-learning",
      roadProgress: 0.74,
      roadSide: 1,
      setback: 6.4,
      footprint: [15, 10],
      height: 7,
      style: "library",
    },
    {
      id: "project-workshop",
      title: "Project Workshop",
      shortTitle: "Projects",
      districtId: "projects",
      kind: "evidence",
      routeOrder: 9,
      roadId: "branch-projects",
      roadProgress: 0.74,
      roadSide: -1,
      setback: 6.4,
      footprint: [16, 10],
      height: 6.5,
      style: "workshop",
    },
    {
      id: "community-hall",
      title: "Community Hall",
      shortTitle: "Community",
      districtId: "community",
      kind: "evidence",
      routeOrder: 10,
      roadId: "branch-community",
      roadProgress: 0.74,
      roadSide: 1,
      setback: 6.4,
      footprint: [16, 11],
      height: 7,
      style: "community",
    },
    {
      id: "contact-pavilion",
      title: "Contact Pavilion",
      shortTitle: "Contact",
      districtId: "contact",
      kind: "contact",
      routeOrder: 11,
      roadId: "spine-contact",
      roadProgress: 0.7,
      roadSide: -1,
      setback: 6.5,
      footprint: [14, 9],
      height: 6,
      style: "pavilion",
    },
  ],
} as const
